### ISSUE TITLE
Public type CycleSortExample not defined in its own file

### ISSUE THREAD

**Issue by ArunVatsyayan** [avantikachauhann/Data-Structures-and-Algorithm#31]
In the `CycleSort.java` file, there is a problem with the `CycleSortExample` class. Java conventions require that each public class should be defined in its own file, which is not the case here. This may lead to compilation errors or unexpected behavior.

The specific error message I'm getting is: "The public type CycleSortExample must be defined in its own file".

Please review this and resolve the issue, or let me know if I can provide any additional information.

**Comment by avantikachauhann** [comment]
Thankyou for the review @ArunVatsyayan
