### ISSUE TITLE
Resource Leak in PalindromeNumber.java

### ISSUE THREAD

**Issue by ArunVatsyayan** [avantikachauhann/Data-Structures-and-Algorithm#32]
In the `PalindromeNumber.java` file, there seems to be a resource leak warning. It appears that the `Scanner` object, 'scanner', is never closed.

The specific warning message I'm seeing is: "Resource leak: 'scanner' is never closed".

This might lead to resource leaks and other unexpected behavior. Please review the code and add necessary `close()` statements or try to use try-with-resources, which ensures that each resource is closed at the end of the statement.

**Comment by avantikachauhann** [comment]
Thank you for bringing the error to my attention.
